In [275]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [276]:
df = pd.read_csv(r'C:\Users\Shivam kumar\Desktop\PROJECT\Electricity-Consumption\notebooks\EDA_Data.csv')
df.head()

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3,Hour,Day,Month,Season
0,2017-01-01 00:00:00,6.19683,75.06667,0.08183,0.06350,0.09883,29197.97468,18026.74772,19252.04819,0,6,1,0
1,2017-01-01 01:00:00,5.54883,77.58333,0.08200,0.05683,0.11250,24657.21519,16078.41945,17042.89157,1,6,1,0
2,2017-01-01 02:00:00,5.05433,78.93333,0.08233,0.06300,0.12917,22083.03797,14330.69909,15676.14458,2,6,1,0
3,2017-01-01 03:00:00,5.00433,77.08333,0.08283,0.05983,0.14100,20811.13924,13219.45289,14883.85542,3,6,1,0
4,2017-01-01 04:00:00,5.09767,74.05000,0.08233,0.05800,0.12283,20475.94937,12921.58055,14317.10843,4,6,1,0

In [277]:
df['Datetime'] = pd.to_datetime(df['Datetime'])
df.set_index('Datetime',inplace=True)

In [278]:
df.corr()

,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3,Hour,Day,Month,Season
Temperature,1.000000,-0.459387,0.479446,0.464366,0.202537,0.443863,0.384833,0.492124,1.974064e-01,-1.372914e-02,2.847331e-01,6.685660e-01
Humidity,-0.459387,1.000000,-0.136835,-0.473566,-0.266270,-0.290764,-0.297885,-0.235100,-2.438862e-01,-1.719812e-02,-1.750506e-02,-6.370457e-02
WindSpeed,0.479446,-0.136835,1.000000,0.136046,-0.001090,0.169573,0.147999,0.280995,4.163587e-03,3.223200e-02,1.689613e-01,4.849304e-01
GeneralDiffuseFlows,0.464366,-0.473566,0.136046,1.000000,0.576290,0.191831,0.159858,0.064914,1.317673e-01,9.799499e-03,-2.083767e-02,1.484461e-01
DiffuseFlows,0.202537,-0.266270,-0.001090,0.576290,1.000000,0.087430,0.049046,-0.037074,1.358580e-01,-2.546732e-02,-1.346856e-01,7.007579e-03
PowerConsumption_Zone1,0.443863,-0.290764,0.169573,0.191831,0.087430,1.000000,0.834165,0.750057,7.343355e-01,-7.031936e-02,-5.392925e-03,2.652575e-01
PowerConsumption_Zone2,0.384833,-0.297885,0.147999,0.159858,0.049046,0.834165,1.000000,0.568448,6.680513e-01,-1.235497e-01,3.225319e-01,7.445393e-02
PowerConsumption_Zone3,0.492124,-0.235100,0.280995,0.064914,-0.037074,0.750057,0.568448,1.000000,4.564253e-01,5.319382e-03,-2.350428e-01,2.649862e-01
Hour,0.197406,-0.243886,0.004164,0.131767,0.135858,0.734335,0.668051,0.456425,1.000000e+00,2.150232e-17,2.562938e-15,6.612910e-16
Day,-0.013729,-0.017198,0.032232,0.009799,-0.025467,-0.070319,-0.123550,0.005319,2.150232e-17,1.000000e+00,6.387829e-03,-8.581654e-03
Month,0.284733,-0.017505,0.168961,-0.020838,-0.134686,-0.005393,0.322532,-0.235043,2.562938e-15,6.387829e-03,1.000000e+00,2.012961e-01
Season,0.668566,-0.063705,0.484930,0.148446,0.007008,0.265257,0.074454,0.264986,6.612910e-16,-8.581654e-03,2.012961e-01,1.000000e+00

In [279]:
df.columns

Index(['Temperature', 'Humidity', 'WindSpeed', 'GeneralDiffuseFlows',
       'DiffuseFlows', 'PowerConsumption_Zone1', 'PowerConsumption_Zone2',
       'PowerConsumption_Zone3', 'Hour', 'Day', 'Month', 'Season'],
      dtype='object')

In [280]:
df.dtypes

Temperature               float64
Humidity                  float64
WindSpeed                 float64
GeneralDiffuseFlows       float64
DiffuseFlows              float64
PowerConsumption_Zone1    float64
PowerConsumption_Zone2    float64
PowerConsumption_Zone3    float64
Hour                        int64
Day                         int64
Month                       int64
Season                      int64
dtype: object

In [281]:
df.duplicated().sum()

0

**TRAINING THE MODEL**

In [282]:
from sklearn.model_selection import train_test_split

In [283]:

from sklearn.metrics import r2_score

In [284]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [285]:
import joblib

In [286]:
# model 1 for zone 1

model1 = RandomForestRegressor() 

x1 = df.drop(['PowerConsumption_Zone1'],axis=1)
y1 = df['PowerConsumption_Zone1']

x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size=0.3,random_state=42)

model1.fit(x1_train,y1_train)
model1_preds = model1.predict(x1_test)

print(f"{r2_score(model1_preds,y1_test)}")

0.9704408929945233

In [287]:
# model 2 for zone 2

model2 = RandomForestRegressor() 


x2 = df.drop(['PowerConsumption_Zone2'],axis=1)
y2 = df['PowerConsumption_Zone2']

x2_train,x2_test,y2_train,y2_test = train_test_split(x2,y2,test_size=0.3,random_state=42)

model2.fit(x2_train,y2_train)
model2_preds = model2.predict(x2_test)

print(f"{r2_score(model2_preds,y2_test)}")

0.9562164490637245

In [288]:
# model 2 for zone 2

model3 = RandomForestRegressor() 

x3 = df.drop(['PowerConsumption_Zone3'],axis=1)
y3 = df['PowerConsumption_Zone3']

x3_train,x3_test,y3_train,y3_test = train_test_split(x3,y3,test_size=0.3,random_state=42)

model3.fit(x3_train,y3_train)
model3_preds = model3.predict(x3_test)

print(f"{r2_score(model3_preds,y3_test)}")

0.9688496284936068

In [289]:
# Saving the model

joblib.dump(model1,"zone1_model.pkl")

joblib.dump(model2,"zone2_model.pkl")

joblib.dump(model3,"zone3_model.pkl")

['zone3_model.pkl']